### ISSUE TITLE
Expand to add AzureRepos not just GitHub

### ISSUE THREAD

**Issue by NarcissaMorton** [Azure/mlops-v2#28]
Would it be possible to expand example to use Azure Repos as well and not just GitHub? We don't use GitHub at all, but are very interested in the MLOps accelerator.

**Comment by setuc** [comment]
@NarcissaMorton There isn't anything specific to GitHub in the repositories unless you are working with GitHub Actions. The accelerator requires two main repos:
1. Main Repo: https://github.com/Azure/mlops-project-template
2. Template Repo: https://github.com/Azure/mlops-templates

The main repo holds your main data science code and the overall pipeline. The template repo contains the individual reusable pipeline steps. To work with Azure repos will be the same as the current step, except your repositories will now be in Azure Repos. 

To use them you will need to clone the two repositories into Azure Repos. Configure the required pipeline files to run the pipelines for the required area (CV/Classical/NLP). 

**What to edit in Pipeline:**
Each of the pipeline script has a connection that you can potentially modify to allow for:

https://github.com/Azure/mlops-project-template/blob/cffdf929008609071b87ab4e8cbb5ff15a600a10/classical/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml#L23-L27

```
  repositories:
    - repository: mlops-templates  # Template Repo --> Use your Azure Repo name here.
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: github-connection # need to set up and hardcode. You will need to configure the connection in Azure DevOps
      type: github # git for Azure Repos
```

You can also refer to this documentation to add appropriate repo in the pipeline. Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

Let us know if you run into specific issues, you can ask them here.
