### ISSUE TITLE
CV Project Template is missing batch endpoint deployment

### ISSUE THREAD

**Issue by azeltov** [Azure/mlops-v2#41]
If you are following the quickstart with CV project template and do batch endpoint deployment the yml file references :

``` 
      - template: templates/${{ variables.version }}/create-deployment.yml@mlops-templates
        parameters:
          deployment_name: taxi-batch-dp
          deployment_file: mlops/azureml/deploy/batch/batch-deployment.yml  
```

![image](https://user-images.githubusercontent.com/5873303/178794383-56c2f132-0168-4c50-8666-87c52062e26e.png)

However the deploy directory in templates for cv flavor only has realtime deployment. Need to either correct the quickstart manual to use real time deployment and/or add batch endpoint support.

![image](https://user-images.githubusercontent.com/5873303/178794983-767b0021-ff36-4c67-a9a0-39a25dbb5b22.png)
