### ISSUE TITLE
When working with Conda, there are no checks on the environment packages

### ISSUE THREAD

**Issue by setuc** [Azure/mlops-v2#79]
### Describe the bug or the issue that you are facing

When creating the environments with conda, there are no checks performed when creating the environment to see if the packages exist or if the pip dependencies are also correctly installed. 

### Steps/Code to Reproduce

When creating the environments with conda, there are no checks performed when creating the environment to see if the packages exist or if the pip dependencies are also correctly installed. 

`az ml environment create --file .\train-conda.yml`

`train-conda.yml`

```yaml
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: docker-image-plus-conda-example
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: environment.yml
description: Environment created from a Docker image plus Conda environment.
```

`environment.yml`
```yaml
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.5
  - pip
  - pip:
      - azureml-mlflow==1.38.0
      - azureml-sdk==1.38.0
      - sklearn==0.24.1
```

### Expected Output

No error is thrown even though there is no such package like sklearn.

There should be a check to make sure that the environment has been successfully created before moving on to the next steps. 

### Versions

 running `az -v`
azure-cli                         2.43.0

core                              2.43.0
telemetry                          1.0.8

Extensions:
account                            0.2.5
ml                                2.12.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Bicep

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML CLI v2

### Describe the example that you are trying to run?

Tabular. but this affects all the environments.
